name: 'Autolabeler'

on:
  # pull_request is required for autolabeler
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  # pull_request_target is required for autolabeler on PRs from forks
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  autolabel:
    name: 'Autolabel PR'
    permissions:
      pull-requests: write
      contents: read
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7