name: Release Drafter

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label-pr:
    name: Update release draft
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
